### ISSUE TITLE
Had this WARN appear in console from the latest dev release, caused by updater?

### ISSUE THREAD

**Issue by axemwa** [TheBusyBiscuit/CS-CoreLib#59] opened 2018-10-08 12:28 UTC
[22:49:35 WARN]: Exception in thread "Thread-16" java.lang.NumberFormatException: For input string: "29(845183)"
[22:49:35 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[22:49:35 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[22:49:35 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[22:49:35 WARN]:        at me.mrCookieSlime.CSCoreLibPlugin.updater.Updater$UpdaterTask.check(Updater.java:107)
[22:49:35 WARN]:        at me.mrCookieSlime.CSCoreLibPlugin.updater.Updater$UpdaterTask.run(Updater.java:59)

**Comment by axemwa** [comment] 2018-10-11 21:49
diabling updates has removed the warning for now

**Comment by axemwa** [comment] 2018-12-28 10:54
Why have you closed it have you added a fix for it, or is there something I can do to fix it?

**Comment by TheBusyBiscuit** [comment] 2018-12-28 11:05
@axemwa The Issue is still open... Noone has closed it...?

**Comment by axemwa** [comment] 2018-12-28 15:37
Sorry I was looking at the wrong thing (#61 ), been up all night my apologies take care...

**Comment by TheBusyBiscuit** [comment] 2019-01-02 13:17
Build 33 and later will now omit the Auto-Updater from freaking out when it sees a dev-build.
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#33

**Closed by TheBusyBiscuit** 2019-01-02 13:17 UTC
