### ISSUE TITLE
Warning on CSCORE29 1.13.2

### ISSUE THREAD

**Issue by Amiroslo** [TheBusyBiscuit/CS-CoreLib#61] opened 2018-10-28 11:35 UTC
When the server finishes loading this comes at the end

`[12:29:57 WARN]: Exception in thread "Thread-18" java.lang.NumberFormatException: For input string: "29(845183)"
[12:29:57 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[12:29:57 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[12:29:57 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[12:29:57 WARN]:        at me.mrCookieSlime.CSCoreLibPlugin.updater.Updater$UpdaterTask.check(Updater.java:107)
[12:29:57 WARN]:        at me.mrCookieSlime.CSCoreLibPlugin.updater.Updater$UpdaterTask.run(Updater.java:59)
[12:29:57 WARN]:        at java.lang.Thread.run(Unknown Source)`

Using Latest SlimeFun4#58 and CSCORE29 on PaperSpigot Build 405 1.13.2

**Comment by TheBusyBiscuit** [comment] 2018-11-01 19:45
Duplicate of #59

**Closed by TheBusyBiscuit** 2018-11-01 19:45 UTC
